version: '3'
services:
  db:
    image: samiraghouri/database:version1
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: reactlibrarydatabase
    volumes:
      - app-volume:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - backend-net

  springboot:
    image: samiraghouri/backend:version1
    ports:
      - "8090:8090"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reactlibrarydatabase?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      OKTA_ISSUER_URI: https://dev-10835870.okta.com/oauth2/default
      OKTA_CLIENT_ID: 0oa91wp8dopyNe9Fv5d7
      OKTA_REDIRECT_URI: http://localhost:3000/login/callback

    volumes:
      - logs-volume:/logs

    networks:
      - backend-net

  reactjs:
    image: samiraghouri/frontend:version1
    ports:
      - "3000:3000"
    depends_on:
      - springboot
    environment:
      OKTA_CLIENT_ID: 0oa91wp8dopyNe9Fv5d7
      OKTA_ISSUER: https://dev-10835870.okta.com/oauth2/default
      OKTA_REDIRECT_URI: http://localhost:3000/login/callback


networks:
  backend-net:

volumes:
  app-volume:
  logs-volume:

